spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zady?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

zady:
  default-avatar: https://i.loli.net/2020/03/21/rtR3HPBNlMUjSAG.jpg
  default-invite-role: developer,tester

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.edu.neu.zady.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      update-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: flag


