spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zady?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.edu.neu.zady.pojo
  configuration:
    map-underscore-to-camel-case: true

zady:
  default-avatar: https://i.loli.net/2020/03/21/rtR3HPBNlMUjSAG.jpg
